### ISSUE TITLE
example of post in laravel

### ISSUE THREAD

**Issue by taylormaguire** [spinen/connectwise-php-client#13] opened 2018-04-26 03:29 UTC
wondering if there is an example of using this to post data to connectwise from laravel. unclear how to add the JSON Body.

**Comment by jimmypuckett** [comment] 2018-07-16 01:19
@taylormaguire,

I am sorry for the delay, we have had a few projects that are eating us alive.  Anyhow, we are about to get on a big project that is going to be using this client, so we will be refining it.

We will add better documentation at that time.

Thanks.

**Comment by jimmypuckett** [comment] 2018-10-18 10:54
Duplicate of #1

**Closed by jimmypuckett** 2018-10-18 10:54 UTC
Labels: question
